export const performanceStatsData = [
  {
    label: "TOTAL INVESTED",
    value: "₹ 18,000",
    trend: "+14.3%",
    trendGreen: true,
    icon: "briefcase",
  },
  {
    label: "CURRENT VALUE",
    value: "₹ 22,600",
    trend: "+₹4.6K gain",
    trendGreen: true,
    icon: "trending-up",
  },
  {
    label: "TOTAL ROI",
    value: "+25.6%",
    trend: "Since first investment",
    trendGreen: false,
    icon: "bar-chart-3",
  },
  {
    label: "WATCHLIST",
    value: "3",
    trend: "3 with auctions",
    trendGreen: false,
    icon: "bookmark",
  },
];

export const monthlyReturnsData = [
  { month: "Jan", value: 5700 },
  { month: "Feb", value: 7800 },
  { month: "Mar", value: 10000 },
  { month: "Apr", value: 11700 },
  { month: "May", value: 13900 },
  { month: "Jun", value: 16000 },
  { month: "Jul", value: 11900 },
  { month: "Aug", value: 18000 },
];

export const aiTableData = [
  {
    initial: "N",
    name: "NeuroPay",
    sector: "FinTech",
    invested: "₹ 4,800",
    currentValue: "₹ 6,200",
    gainLoss: "+₹ 1,400",
    gainPositive: true,
    roi: "+ 29.2%",
    roiPositive: true,
  },
  {
    initial: "G",
    name: "GreenChain",
    sector: "Climatech",
    invested: "₹ 2,000",
    currentValue: "₹ 2,840",
    gainLoss: "+₹ 840",
    gainPositive: true,
    roi: "+ 42%",
    roiPositive: true,
  },
  {
    initial: "Q",
    name: "QuantumLens",
    sector: "AR/VR",
    invested: "₹ 5,200",
    currentValue: "₹ 6,100",
    gainLoss: "+₹ 900",
    gainPositive: true,
    roi: "+ 17.3%",
    roiPositive: true,
  },
  {
    initial: "F",
    name: "FlowFinance",
    sector: "DeFi",
    invested: "₹ 3,000",
    currentValue: "₹ 4,200",
    gainLoss: "+₹ 1,200",
    gainPositive: true,
    roi: "+ 40%",
    roiPositive: true,
  },
  {
    initial: "D",
    name: "DataVault",
    sector: "Web3",
    invested: "₹ 1,500",
    currentValue: "₹ 1,780",
    gainLoss: "+₹ 280",
    gainPositive: true,
    roi: "+ 18.7%",
    roiPositive: true,
  },
  {
    initial: "M",
    name: "MetaStudio",
    sector: "Creator",
    invested: "₹ 1,500",
    currentValue: "₹ 1,480",
    gainLoss: "-₹ 30",
    gainPositive: false,
    roi: "- 13.3%",
    roiPositive: false,
  },
];
