export const companiesData = [
  {
    id: 1,
    initial: "N",
    name: "NeuroPay",
    price: 4800,
    tokenPrice: 6200,
    domain: "FinTech",
    status: "Listed",
  },
  {
    id: 2,
    initial: "Q",
    name: "QuantumLens",
    price: 2500,
    tokenPrice: 6200,
    domain: "AR/VR",
    status: "Listed",
  },
  {
    id: 3,
    initial: "F",
    name: "FlowFinance",
    price: 1100,
    tokenPrice: 6200,
    domain: "FinTech",
    status: "Listed",
  },
  {
    id: 4,
    initial: "D",
    name: "DataVault",
    price: 4900,
    tokenPrice: 6200,
    domain: "FinTech",
    status: "Listed",
  },
  {
    id: 5,
    initial: "G",
    name: "GreenGrid",
    price: 3200,
    tokenPrice: 8900,
    domain: "CleanTech",
    status: "Unlisted",
  },
  {
    id: 6,
    initial: "M",
    name: "MedSync",
    price: 5800,
    tokenPrice: 7500,
    domain: "HealthTech",
    status: "Listed",
  },
  {
    id: 7,
    initial: "S",
    name: "StackFlow",
    price: 2100,
    tokenPrice: 4100,
    domain: "DevTools",
    status: "Listed",
  },
  {
    id: 8,
    initial: "A",
    name: "AeroSense",
    price: 4700,
    tokenPrice: 11200,
    domain: "Aerospace",
    status: "Unlisted",
  },
  {
    id: 9,
    initial: "V",
    name: "VaultEdge",
    price: 6400,
    tokenPrice: 13400,
    domain: "CyberSecurity",
    status: "Listed",
  },
  {
    id: 10,
    initial: "N",
    name: "NovaTech",
    price: 3900,
    tokenPrice: 9800,
    domain: "AI/ML",
    status: "Unlisted",
  },
  {
    id: 11,
    initial: "B",
    name: "BioVault",
    price: 5200,
    tokenPrice: 10300,
    domain: "BioTech",
    status: "Listed",
  },
  {
    id: 12,
    initial: "S",
    name: "SkyLens",
    price: 2800,
    tokenPrice: 7600,
    domain: "SpaceTech",
    status: "Unlisted",
  },
  {
    id: 13,
    initial: "D",
    name: "DataWeave",
    price: 3400,
    tokenPrice: 6100,
    domain: "Big Data",
    status: "Listed",
  },
  {
    id: 14,
    initial: "E",
    name: "EcoCharge",
    price: 7100,
    tokenPrice: 15600,
    domain: "Energy",
    status: "Unlisted",
  },
  {
    id: 15,
    initial: "P",
    name: "PixelForge",
    price: 1900,
    tokenPrice: 3300,
    domain: "Gaming",
    status: "Listed",
  },
  {
    id: 16,
    initial: "O",
    name: "OceanView",
    price: 2600,
    tokenPrice: 5400,
    domain: "BlueTech",
    status: "Unlisted",
  },
];
