// Helper: create a future end time (N hours from now)
function hoursFromNow(hours) {
  return new Date(Date.now() + hours * 3600 * 1000).toISOString();
}

// Helper: create a past start time (N days ago)
function daysAgo(days) {
  return new Date(Date.now() - days * 24 * 3600 * 1000).toISOString();
}

export const liveAuctions = [
  {
    id: 1,
    companyName: "NeuroPay",
    logoLetter: "N",
    sector: "FinTech",
    description: "AI-powered payment infrastructure for enterprise businesses with real-time cross-border settlement.",
    tokenName: "Neuro",
    tokenTicker: "NRP",
    tokenSupply: "50,00,000 NRP",
    pricePerToken: "₹ 2.00",
    tokenAmount: "500 NRP",
    vestingPeriod: "12 months linear",
    status: "live",
    currentBid: 1000,
    targetAmount: 10000,
    equityPercent: 30,
    avgBid: 6200,
    progressPercent: 62,
    endTime: hoursFromNow(4),
    startDate: daysAgo(3),
    txHash: "0xa1b2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef",
  },
  {
    id: 2,
    companyName: "GreenGrid",
    logoLetter: "G",
    sector: "CleanTech",
    description: "Decentralized renewable energy marketplace connecting producers with commercial buyers.",
    tokenName: "Green",
    tokenTicker: "GRD",
    tokenSupply: "25,00,000 GRD",
    pricePerToken: "₹ 3.50",
    tokenAmount: "714 GRD",
    vestingPeriod: "6 months cliff + 12 months linear",
    status: "live",
    currentBid: 2500,
    targetAmount: 15000,
    equityPercent: 25,
    avgBid: 8900,
    progressPercent: 45,
    endTime: hoursFromNow(8),
    startDate: daysAgo(5),
    txHash: "0xb2c3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef1",
  },
  {
    id: 3,
    companyName: "MedSync",
    logoLetter: "M",
    sector: "HealthTech",
    description: "Cloud-based patient data interoperability platform for hospitals and clinics.",
    tokenName: "Med",
    tokenTicker: "MDS",
    tokenSupply: "75,00,000 MDS",
    pricePerToken: "₹ 1.20",
    tokenAmount: "833 MDS",
    vestingPeriod: "24 months linear",
    status: "live",
    currentBid: 3200,
    targetAmount: 12000,
    equityPercent: 20,
    avgBid: 7500,
    progressPercent: 73,
    endTime: hoursFromNow(2),
    startDate: daysAgo(2),
    txHash: "0xc3d4e5f678901234567890abcdef1234567890abcdef1234567890abcdef12",
  },
  {
    id: 4,
    companyName: "StackFlow",
    logoLetter: "S",
    sector: "DevTools",
    description: "Visual pipeline builder for backend infrastructure with one-click cloud deployment.",
    tokenName: "Stack",
    tokenTicker: "STK",
    tokenSupply: "1,00,00,000 STK",
    pricePerToken: "₹ 0.80",
    tokenAmount: "1,250 STK",
    vestingPeriod: "12 months linear",
    status: "live",
    currentBid: 1800,
    targetAmount: 8000,
    equityPercent: 15,
    avgBid: 4100,
    progressPercent: 55,
    endTime: hoursFromNow(12),
    startDate: daysAgo(4),
    txHash: "0xd4e5f678901234567890abcdef1234567890abcdef1234567890abcdef123",
  },
  {
    id: 5,
    companyName: "AeroSense",
    logoLetter: "A",
    sector: "Aerospace",
    description: "Drone-based environmental monitoring system using edge AI and computer vision.",
    tokenName: "Aero",
    tokenTicker: "ARN",
    tokenSupply: "10,00,000 ARN",
    pricePerToken: "₹ 5.00",
    tokenAmount: "200 ARN",
    vestingPeriod: "6 months cliff + 18 months linear",
    status: "live",
    currentBid: 4500,
    targetAmount: 20000,
    equityPercent: 18,
    avgBid: 11200,
    progressPercent: 38,
    endTime: hoursFromNow(6),
    startDate: daysAgo(6),
    txHash: "0xe5f678901234567890abcdef1234567890abcdef1234567890abcdef1234",
  },
  {
    id: 6,
    companyName: "VaultEdge",
    logoLetter: "V",
    sector: "CyberSecurity",
    description: "Zero-trust identity and access management platform for remote-first organizations.",
    tokenName: "Vault",
    tokenTicker: "VLT",
    tokenSupply: "30,00,000 VLT",
    pricePerToken: "₹ 4.20",
    tokenAmount: "238 VLT",
    vestingPeriod: "12 months linear",
    status: "live",
    currentBid: 5000,
    targetAmount: 18000,
    equityPercent: 22,
    avgBid: 13400,
    progressPercent: 81,
    endTime: hoursFromNow(1),
    startDate: daysAgo(1),
    txHash: "0xf678901234567890abcdef1234567890abcdef1234567890abcdef12345",
  },
];

export const upcomingAuctions = [
  {
    id: 7,
    companyName: "NovaTech",
    logoLetter: "N",
    sector: "AI/ML",
    description: "Generative AI platform for automated code review and vulnerability detection.",
    tokenName: "Nova",
    tokenTicker: "NOV",
    tokenSupply: "1,00,00,000 NOV",
    pricePerToken: "₹ 1.50",
    tokenAmount: "1,667 NOV",
    vestingPeriod: "12 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 25000,
    equityPercent: 20,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(12),
  },
  {
    id: 8,
    companyName: "BioVault",
    logoLetter: "B",
    sector: "BioTech",
    description: "CRISPR-based gene editing toolkit for agricultural crop resilience.",
    tokenName: "Bio",
    tokenTicker: "BVL",
    tokenSupply: "50,00,000 BVL",
    pricePerToken: "₹ 6.00",
    tokenAmount: "833 BVL",
    vestingPeriod: "18 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 30000,
    equityPercent: 18,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(24),
  },
  {
    id: 9,
    companyName: "SkyLens",
    logoLetter: "S",
    sector: "SpaceTech",
    description: "Satellite-based real-time agricultural monitoring with hyperspectral imaging.",
    tokenName: "Sky",
    tokenTicker: "SKY",
    tokenSupply: "40,00,000 SKY",
    pricePerToken: "₹ 3.00",
    tokenAmount: "667 SKY",
    vestingPeriod: "6 months cliff + 12 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 20000,
    equityPercent: 22,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(48),
  },
  {
    id: 10,
    companyName: "DataWeave",
    logoLetter: "D",
    sector: "Big Data",
    description: "Serverless data lakehouse platform for real-time analytics at scale.",
    tokenName: "Weave",
    tokenTicker: "WEV",
    tokenSupply: "2,00,00,000 WEV",
    pricePerToken: "₹ 0.50",
    tokenAmount: "3,600 WEV",
    vestingPeriod: "12 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 18000,
    equityPercent: 15,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(36),
  },
  {
    id: 11,
    companyName: "EcoCharge",
    logoLetter: "E",
    sector: "Energy",
    description: "Wireless EV charging infrastructure using resonant inductive coupling.",
    tokenName: "Eco",
    tokenTicker: "ECH",
    tokenSupply: "60,00,000 ECH",
    pricePerToken: "₹ 2.50",
    tokenAmount: "1,400 ECH",
    vestingPeriod: "12 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 35000,
    equityPercent: 25,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(60),
  },
  {
    id: 12,
    companyName: "PixelForge",
    logoLetter: "P",
    sector: "Gaming",
    description: "Procedural 3D asset generation engine for indie game developers.",
    tokenName: "Pixel",
    tokenTicker: "PNG",
    tokenSupply: "80,00,000 PNG",
    pricePerToken: "₹ 1.00",
    tokenAmount: "1,200 PNG",
    vestingPeriod: "12 months linear",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 12000,
    equityPercent: 12,
    avgBid: 0,
    progressPercent: 0,
    startDate: hoursFromNow(72),
  },
];

export const closedAuctions = [
  {
    id: 13,
    companyName: "QuantumLeap",
    logoLetter: "Q",
    sector: "Quantum",
    description: "Hybrid quantum-classical optimization solver for logistics and supply chain.",
    tokenName: "Quantum",
    tokenTicker: "QTM",
    tokenSupply: "20,00,000 QTM",
    pricePerToken: "₹ 7.50",
    tokenAmount: "200 QTM",
    vestingPeriod: "24 months linear",
    status: "closed",
    currentBid: 8500,
    targetAmount: 15000,
    equityPercent: 20,
    avgBid: 7200,
    progressPercent: 100,
    endDate: daysAgo(14),
  },
  {
    id: 14,
    companyName: "OceanView",
    logoLetter: "O",
    sector: "BlueTech",
    description: "Underwater IoT sensor network for real-time ocean data collection.",
    tokenName: "Ocean",
    tokenTicker: "OCN",
    tokenSupply: "35,00,000 OCN",
    pricePerToken: "₹ 4.80",
    tokenAmount: "292 OCN",
    vestingPeriod: "12 months linear",
    status: "closed",
    currentBid: 6200,
    targetAmount: 12000,
    equityPercent: 18,
    avgBid: 5400,
    progressPercent: 100,
    endDate: daysAgo(21),
  },
  {
    id: 15,
    companyName: "AgriBot",
    logoLetter: "A",
    sector: "AgriTech",
    description: "Autonomous robotic harvesting system for vertical farms and greenhouses.",
    tokenName: "Agri",
    tokenTicker: "AGB",
    tokenSupply: "45,00,000 AGB",
    pricePerToken: "₹ 3.20",
    tokenAmount: "375 AGB",
    vestingPeriod: "12 months linear",
    status: "closed",
    currentBid: 12000,
    targetAmount: 25000,
    equityPercent: 25,
    avgBid: 9800,
    progressPercent: 100,
    endDate: daysAgo(30),
  },
  {
    id: 16,
    companyName: "CyberShield",
    logoLetter: "C",
    sector: "CyberSecurity",
    description: "AI-driven threat detection platform for zero-day vulnerability discovery.",
    tokenName: "Shield",
    tokenTicker: "SHD",
    tokenSupply: "50,00,000 SHD",
    pricePerToken: "₹ 5.50",
    tokenAmount: "182 SHD",
    vestingPeriod: "12 months linear",
    status: "closed",
    currentBid: 15000,
    targetAmount: 22000,
    equityPercent: 15,
    avgBid: 13100,
    progressPercent: 100,
    endDate: daysAgo(7),
  },
  {
    id: 17,
    companyName: "NanoMed",
    logoLetter: "N",
    sector: "MedTech",
    description: "Nanoparticle drug delivery platform for targeted cancer therapeutics.",
    tokenName: "Nano",
    tokenTicker: "NMD",
    tokenSupply: "25,00,000 NMD",
    pricePerToken: "₹ 6.80",
    tokenAmount: "135 NMD",
    vestingPeriod: "18 months linear",
    status: "closed",
    currentBid: 9200,
    targetAmount: 18000,
    equityPercent: 22,
    avgBid: 8100,
    progressPercent: 100,
    endDate: daysAgo(23),
  },
  {
    id: 18,
    companyName: "UrbanFlow",
    logoLetter: "U",
    sector: "SmartCity",
    description: "AI-powered traffic optimization platform for smart city infrastructure.",
    tokenName: "Urban",
    tokenTicker: "URF",
    tokenSupply: "65,00,000 URF",
    pricePerToken: "₹ 2.40",
    tokenAmount: "312 URF",
    vestingPeriod: "12 months linear",
    status: "closed",
    currentBid: 7500,
    targetAmount: 14000,
    equityPercent: 16,
    avgBid: 6600,
    progressPercent: 100,
    endDate: daysAgo(18),
  },
];
