export const liveAuctions = [
  {
    id: 1,
    companyName: "NeuroPay",
    logoLetter: "N",
    sector: "FinTech",
    description: "AI-powered payment infrastructure for enterprise businesses with real-time cross-border settlement.",
    status: "live",
    currentBid: 1000,
    targetAmount: 10000,
    equityPercent: 30,
    avgBid: 6200,
    progressPercent: 62,
  },
  {
    id: 2,
    companyName: "GreenGrid",
    logoLetter: "G",
    sector: "CleanTech",
    description: "Decentralized renewable energy marketplace connecting producers with commercial buyers.",
    status: "live",
    currentBid: 2500,
    targetAmount: 15000,
    equityPercent: 25,
    avgBid: 8900,
    progressPercent: 45,
  },
  {
    id: 3,
    companyName: "MedSync",
    logoLetter: "M",
    sector: "HealthTech",
    description: "Cloud-based patient data interoperability platform for hospitals and clinics.",
    status: "live",
    currentBid: 3200,
    targetAmount: 12000,
    equityPercent: 20,
    avgBid: 7500,
    progressPercent: 73,
  },
  {
    id: 4,
    companyName: "StackFlow",
    logoLetter: "S",
    sector: "DevTools",
    description: "Visual pipeline builder for backend infrastructure with one-click cloud deployment.",
    status: "live",
    currentBid: 1800,
    targetAmount: 8000,
    equityPercent: 15,
    avgBid: 4100,
    progressPercent: 55,
  },
  {
    id: 5,
    companyName: "AeroSense",
    logoLetter: "A",
    sector: "Aerospace",
    description: "Drone-based environmental monitoring system using edge AI and computer vision.",
    status: "live",
    currentBid: 4500,
    targetAmount: 20000,
    equityPercent: 18,
    avgBid: 11200,
    progressPercent: 38,
  },
  {
    id: 6,
    companyName: "VaultEdge",
    logoLetter: "V",
    sector: "CyberSecurity",
    description: "Zero-trust identity and access management platform for remote-first organizations.",
    status: "live",
    currentBid: 5000,
    targetAmount: 18000,
    equityPercent: 22,
    avgBid: 13400,
    progressPercent: 81,
  },
];

export const upcomingAuctions = [
  {
    id: 7,
    companyName: "NovaTech",
    logoLetter: "N",
    sector: "AI/ML",
    description: "Generative AI platform for automated code review and vulnerability detection.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 25000,
    equityPercent: 20,
    avgBid: 0,
    progressPercent: 0,
  },
  {
    id: 8,
    companyName: "BioVault",
    logoLetter: "B",
    sector: "BioTech",
    description: "CRISPR-based gene editing toolkit for agricultural crop resilience.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 30000,
    equityPercent: 18,
    avgBid: 0,
    progressPercent: 0,
  },
  {
    id: 9,
    companyName: "SkyLens",
    logoLetter: "S",
    sector: "SpaceTech",
    description: "Satellite-based real-time agricultural monitoring with hyperspectral imaging.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 20000,
    equityPercent: 22,
    avgBid: 0,
    progressPercent: 0,
  },
  {
    id: 10,
    companyName: "DataWeave",
    logoLetter: "D",
    sector: "Big Data",
    description: "Serverless data lakehouse platform for real-time analytics at scale.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 18000,
    equityPercent: 15,
    avgBid: 0,
    progressPercent: 0,
  },
  {
    id: 11,
    companyName: "EcoCharge",
    logoLetter: "E",
    sector: "Energy",
    description: "Wireless EV charging infrastructure using resonant inductive coupling.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 35000,
    equityPercent: 25,
    avgBid: 0,
    progressPercent: 0,
  },
  {
    id: 12,
    companyName: "PixelForge",
    logoLetter: "P",
    sector: "Gaming",
    description: "Procedural 3D asset generation engine for indie game developers.",
    status: "upcoming",
    currentBid: 0,
    targetAmount: 12000,
    equityPercent: 12,
    avgBid: 0,
    progressPercent: 0,
  },
];

export const closedAuctions = [
  {
    id: 13,
    companyName: "QuantumLeap",
    logoLetter: "Q",
    sector: "Quantum",
    description: "Hybrid quantum-classical optimization solver for logistics and supply chain.",
    status: "closed",
    currentBid: 8500,
    targetAmount: 15000,
    equityPercent: 20,
    avgBid: 7200,
    progressPercent: 100,
  },
  {
    id: 14,
    companyName: "OceanView",
    logoLetter: "O",
    sector: "BlueTech",
    description: "Underwater IoT sensor network for real-time ocean data collection.",
    status: "closed",
    currentBid: 6200,
    targetAmount: 12000,
    equityPercent: 18,
    avgBid: 5400,
    progressPercent: 100,
  },
  {
    id: 15,
    companyName: "AgriBot",
    logoLetter: "A",
    sector: "AgriTech",
    description: "Autonomous robotic harvesting system for vertical farms and greenhouses.",
    status: "closed",
    currentBid: 12000,
    targetAmount: 25000,
    equityPercent: 25,
    avgBid: 9800,
    progressPercent: 100,
  },
  {
    id: 16,
    companyName: "CyberShield",
    logoLetter: "C",
    sector: "CyberSecurity",
    description: "AI-driven threat detection platform for zero-day vulnerability discovery.",
    status: "closed",
    currentBid: 15000,
    targetAmount: 22000,
    equityPercent: 15,
    avgBid: 13100,
    progressPercent: 100,
  },
  {
    id: 17,
    companyName: "NanoMed",
    logoLetter: "N",
    sector: "MedTech",
    description: "Nanoparticle drug delivery platform for targeted cancer therapeutics.",
    status: "closed",
    currentBid: 9200,
    targetAmount: 18000,
    equityPercent: 22,
    avgBid: 8100,
    progressPercent: 100,
  },
  {
    id: 18,
    companyName: "UrbanFlow",
    logoLetter: "U",
    sector: "SmartCity",
    description: "AI-powered traffic optimization platform for smart city infrastructure.",
    status: "closed",
    currentBid: 7500,
    targetAmount: 14000,
    equityPercent: 16,
    avgBid: 6600,
    progressPercent: 100,
  },
];
