export const watchlistCompanies = [
  {
    id: 1,
    initial: "N",
    name: "NeuroPay",
    raised: "₹ 2.4M raised",
    category: "FinTech",
    growth: "+38% growth",
    growthGreen: true,
    progress: 48,
  },
  {
    id: 2,
    initial: "G",
    name: "GreenChain",
    raised: "₹ 800k raised",
    category: "ClimaTech",
    growth: "+67% growth",
    growthGreen: true,
    progress: 40,
  },
  {
    id: 3,
    initial: "F",
    name: "FlowFinance",
    raised: "₹ 1.2M raised",
    category: "DeFi",
    growth: "+112% growth",
    growthGreen: true,
    progress: 40,
  },
  {
    id: 4,
    initial: "M",
    name: "MetaStudio",
    raised: "₹ 250k raised",
    category: "Creator Economy",
    growth: "+145% growth",
    growthGreen: true,
    progress: 25,
  },
  {
    id: 5,
    initial: "G",
    name: "GreenChain",
    raised: "₹ 800k raised",
    category: "ClimaTech",
    growth: "+67% growth",
    growthGreen: true,
    progress: 40,
  },
];
